export default [
    'Arial',
    'Arial Black',
    'Arial Light',
    'Arial Narrow',
    'Arial Black',
    'Arial CE',
    'Arial CE MT Black',
    'Comic Neue',
    'Comic Neue Light',
    'DejaVu Sans',
    'DejaVu Sans Light',
    'DejaVu Sans Condensed',
    'Fredericka the Great',
    'Libre Baskerville',
    'Luckiest Guy',
    'Nanum Pen',
    'Noto Sans Arabic',
    'Noto Sans TC',
    'Noto Sans TC Black',
    'Noto Sans TC ExtraBold',
    'Noto Sans TC ExtraLight',
    'Noto Sans TC Light',
    'Noto Sans TC Medium',
    'Noto Sans TC SemiBold',
    'Noto Sans TC Thin',
    'Nunito ExtraLight',
    'Oswald',
    'Pacifico',
    'Permanent Marker',
    'Roboto',
    'Roboto Black',
    'Roboto Light',
    'Roboto Medium',
    'Roboto Thin',
    'Shrikhand',
    'The Bold Font',
];
